---
version: '3'
services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: always
    networks:
      - nodes_network
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /mnt/volume_lon1_05/:/mnt/volume_lon1_05/:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|host|etc)($$|/)'
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - nodes_network
networks:
  nodes_network:
    external:
      name: nodes_network
