---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: default
spec:
  encryptedData:
    redis-password: AgBm3Pi2prRK1F2a+cWWRa6Fes6hNaaOOW8ELeaA1Fvig9hzWwwhbnz5Y0Sg6OrmPFiNtCVyfQtd1MOauLyQWdUbIpw1YjdIU6D0C8zl+d/aVKG9JfmI6xfBoi73O2kCsI8ChUJWk3E4igyXTp57siLen4TQrGEWn8yZVOHKubUZ2je3K3H80Ixkkje6yyPLAjPIzMhQPIEpSEBCGtQ4B8+epAhShdPkQgjdpYVDtQ1dMrqcQkaXmDZzbyVzCoiq/bCbJEFOG66ACAHWk43BIza2s3X1KuKiFrg9CU5KVO4vZG4UL0nKSEZ2mqjZw+YI2slxQ/ZDTjz4cTDV8vjKzyHJx1Xt5HR6pmkjWmh6ye20lMCBIPyGPfkOsJZzo7j80RPdpsmugtqzbApL1WvkndzW6DIvg6TLuYatFTDCyE+QbxdeORASVT0B7aNAAbhz54Q3tnKzL4Ptu+rbAthVMdwGdI9zBS0PIAk+Ks0GF2VQWWPBsWvq0QLuTdQ+5w1AQDqDToA3QcM/VhxH1bWaz8nJCKqdV9bIeOJpFDpwHtqYMGuZa9adW63WWwIhDrfxnLOlp5FQ6ivBiq7vjuGWlRzjeERh2LNv0J9zQZY36R/YYrctUkPJKgorPRJ/hpYqOtLR2U0+JvqCP6/ELMaVdGzdMTakaafsOXgZw4hiFTNS9i144hNawoZuklT/89pPRUmPESWhHYFNzxiVs8PuLnhL
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: default
