---
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: elastic
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 37.2.0
    chart: kube-prometheus-stack-37.2.0
    heritage: Helm
    release: monitoring
  name: elastic
  namespace: monitoring
subsets:
  - addresses:
      - ip: 46.38.255.32
    ports:
      - name: mon
        port: 9108
