---
apiVersion: v1
kind: Service
metadata:
    annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
    name: elastic
    namespace: monitoring
    labels:
        app: elastic
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 37.2.0
        chart: kube-prometheus-stack-37.2.0
        heritage: Helm
        release: monitoring
spec:
    clusterIP: None
    ports:
    - name: mon
      targetPort: mon
      port: 9108
