---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-secret
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgBvc5wjy7L75Q68fVxI3AtHwOyv2rNyLbuAVxjdobWS8BGO0CUlDzVfpqSTWN2pr+2kU8G5L6usaA++7VZAaP5O0GPRHIxMC2faLOGljca39ub/0zOnXoFcoO+khfFWJ+Q3snKKHveuH6IBQmMPYspnfGgIEp2xMDh7B4tIqGAuA0o5IvFsr+2RNliuILe+DaZ1XnYBAPS392Mpa/uwzC+6eQnslYtP8payD+qOO2m+jOD2F983mfRe/56uEQNuprKIQjYUdW8rOybA8YiALS/cSWtIZaEwmDtLwpgfEDcccXUGUS+xQy8K8wZRcd3Wmn5E/B3D7+yergCtD7tHlkdG842pqdoUBj7/KXvT3vtPGJE0r+lK8UkBW7bPg2sy/9FZ1FWxOHLMP6DWELVVZzBnw4pRnvMVeg9lVUCgT4JTB4UkRPmfV+U9NmGU1O5gMyeT7ERKm+4MD8DyPkQXVDsa9xvTYJ9a4Dysj1+ojNibvE+1Pf8MBZuuQX1OYwMrmAE6fe9MFWRgRWuZqr21x0uVc6XF6sEmeCWrhqg8wo12ZY1eMpjWiHv2QHZwpWKPvJcUrqiV5wSzrITgrF/2GhqeSsgg0cw+NDNNQiTjqRD/LiTq+IsFaBsaO5GFdjfe4A/JRkztmaUg2v0JX7STBI32OE+Y0HXBOeJFpQ1dOc26JVCacLEoD6Fhatet59NRlN/L0XXIVIXOfFsNUq81NawB5hwsmDHZynqKdoUT4ChtPMn79T1VPnLOx7uK5n8rb0sUtpnaePGR25i+AI04kNzoms/gQK/zudo/FfsSwCJ58W859VvOixcACR1gqMbbVfDQF7mUJ+0i/N0GP4fKIYsuZhpAOwNNEsE=
  template:
    metadata:
      creationTimestamp: null
      name: discord-secret
      namespace: monitoring
