---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - botkube.yaml
  - metrics-server.yaml
  - sealed-secrets.yaml
  - loki.yaml
  - fluent-bit.yaml
  - monitoring.yaml
  - nginx-ingress.yaml
  - k8s-secrets.yaml
  - subid-nginx.yaml
  - redis.yaml

patches:
  - path: targetRevision.patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
