---
namespace: kube-system

# external secrets helm chart
helmCharts:
  - name: metrics-server
    repo: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.8.3
    releaseName: metrics-server
    namespace: kube-system
    valuesFile: values.yaml
