---
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: rpc2
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 21.0.4
    chart: kube-prometheus-stack-21.0.4
    heritage: Helm
    release: monitoring
  name: rpc2
  namespace: monitoring
subsets:
  - addresses:
      - ip: 89.58.52.180
    ports:
      - name: rpc2
        port: 9615
