---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-subsocial-repo-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: argocd-secret-store
    kind: SecretStore
  target:
    name: github-subsocial-repo-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
  data:
    - secretKey: type
      remoteRef:
        key: k8s/argocd/github-subsocial-repo-creds
        property: type
    - secretKey: url
      remoteRef:
        key: k8s/argocd/github-subsocial-repo-creds
        property: url
    - secretKey: githubAppInstallationID
      remoteRef:
        key: k8s/argocd/github-subsocial-repo-creds
        property: githubAppInstallationID
    - secretKey: githubAppID
      remoteRef:
        key: k8s/argocd/github-subsocial-repo-creds
        property: githubAppID
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: k8s/argocd/github-subsocial-repo-creds
        property: githubAppPrivateKey
