---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.4/manifests/install.yaml

resources:
  - secrets.yaml
  - application.yaml

patchesStrategicMerge:
  - configmap.yaml
  - rm-deployment.yaml
