---
apiVersion: v1
kind: Secret
metadata:
  name: github-subsocial-ops-tools-repository
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: git@github.com:dappforce/ops-tools
