---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: faucet-testnet-secret
  namespace: faucet
spec:
  encryptedData:
    BOT_TOKEN: AgAlGS8wO0pNKzSgfmMZQEXgjHJp8Qe/O+Ght5zvN1w6cmIaw4Yd4pniXHQJVVa5Y0DJDoHWso8qefzX2nYOqgEP5GokBdjp49XdJqFyGcEISlzzsfJDOQ2EwtEQ8WIpk2ixBZL7QsMSnjZExnbvbwzhM9tw6oB3yls8MZ5IZUZxPkrmpi7bR3ko2KNZ3ysTZNfjcyBSel0kWVR0B/bjNMk4quhL/CB/L+Mok1KAXZYey7pXXmcC4qV4xphn68vRAg4Fz+5Sq5U3RAPal9aoyIMoQT3CjhJWKbXhFFglmfgMy8XJxH6uOmoNuDZDZ2BsX8Awbji9UHkeQNCUN7nhWfcQ45XvEJuVvCJNGlTHSCnwb7wk5gnDdNQObemDS2ZeCnJ0HINQi+TcJPauDMhpQajnGAVM1scEy28HlAQJwWApVeH5m/kSavF/jxW4chvasb4u4qimb453vyfA7mHJ5n+VyOlQW63+SD7vOjR7j2fLcrLD4aJ2ekvnGmfts10f7rQKanIZjr3dMTydvtNdfAfeZeOcbFhbDSpgWUnIqlcn0qdtGyzrikCSqOhTA0amtIRIhajmEiD2C6kB/V9S55wSxJQ+Mlq0DQ+iIbTYg6cvWHmvbNQrKGm6oVeyTGEmS3XVynKt+vPK8ift9FdtFvCyMMJ0z75BZc0i3+Y/I2kw/Zt+XRfu128cwrHkSwpnhpDq2CwbpphcwFW9BHMOCKUNzSTfh41V/Niw4ht/GBm9DzGB6APBDRgtfWZjnKZLJO3Hr4D893YTCJW3kw==
    MNEMONIC: AgAcv/csGhzdnmbrKNqb9wu3H/nMoFagTz60BzNSXAm0+qYUQfudoQWbA6q+1Iwsil2pjVb9ZbDCsy9MpnqfnWx1XYuHpmC19P2UX+fv+JPsDaVI0qeh71Id5YYnTqdeYmeNdEc53/mC0hwDnnjsDL1QCR3ht6d+PkYXzADEp6JGIy1jFM8Lk74eZSl3IcrLIl89O1QdYJKvDS5yPOyqGmaBLem9JnyB6B5i8BjQrA0c3yJCh5FPkKO2A86BDLP1DOSS8auhySmKqrLSeXszASeCoFhra8IuudokSKidg+OunJnFzEuEHqkiZBYrRldAonN4rJvBq2nEYMQPPlek7IYsmD1HIJCZUT358zJIMHqQmIeqQ+Q7thT02dLeaYr4b7nJjtqWtQJ4kWJ68gDrDmD2wwX1Tes8rym04HqlCykGRryiTlC354PMS0ElZNke/GWj+5LWnBcgfut1mUiA7KZ0kCQ/vHBVBoGaJ3dViVaMynqhnRteWpu59GMmYbttta4K2vj8h4mA0b3hQWRo2DXM6gFsXcwiFE+J4moeeHTo8wYYfkuqKgneP35rFTEP7NSeWeg5YqralHoy8ingcdQUklfTfzcABNRfZqkE1Gj1PR9WWalgtbFSKL9XbPcZ3TV9ix1/a7n05Idzf86w/P+DYok2aOLRxhyEBv7hW2M6Jq3TXzmBW2larEy/EfcaYpTeqXESDdCdpkKv8g6be0AW48J4yZ1swQbRk7MXcCTwdfBJgXbvM3XqVvdMWil3wx/AvImIPBZIQq6/iM9yEhA1LAgckqQHyf8wLg==
  template:
    metadata:
      creationTimestamp: null
      name: faucet-testnet-secret
      namespace: faucet
