---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  source:
    path: kubernetes/applications/overlays/staging
    targetRevision: main
