---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: __not-used__
spec:
  project: default
  source:
    repoURL: "git@github.com:dappforce/ops-tools"
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
