---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-cluster
spec:
  ports:
    - name: swarm
      nodePort: 32583
      port: 4001
      protocol: TCP
      targetPort: swarm
    - name: swarm-udp
      nodePort: 31690
      port: 4002
      protocol: TCP
      targetPort: swarm-udp
    - name: api
      nodePort: 32175
      port: 5001
      protocol: TCP
      targetPort: api
    - name: ws
      nodePort: 32733
      port: 8081
      protocol: TCP
      targetPort: ws
    - name: http
      nodePort: 30911
      port: 8080
      protocol: TCP
      targetPort: http
    - name: api-http
      nodePort: 32655
      port: 9094
      protocol: TCP
      targetPort: api-http
    - name: proxy-http
      nodePort: 31727
      port: 9095
      protocol: TCP
      targetPort: proxy-http
    - name: cluster-swarm
      nodePort: 32209
      port: 9096
      protocol: TCP
      targetPort: cluster-swarm
  sessionAffinity: None
  type: LoadBalancer
