---
resources:
  - namespace.yaml

# sealed-secret helm chart
helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.7.6
    releaseName: sealed-secrets-controller
    namespace: sealed-secret
    valuesFile: values.yaml

generatorOptions:
  disableNameSuffixHash: true
