---
fullnameOverride: "sealed-secrets-controller"
secretName: "sealed-secrets-key"
updateStatus: false
skipRecreate: true
keyrenewperiod: "0"
resources:
  limits:
    cpu: 150m
    memory: 256Mi
  requests:
    cpu: 150m
    memory: 256Mi
serviceAccount:
  create: true
