---
apiVersion: v1
kind: Service
metadata:
    annotations:
        meta.helm.sh/release-name: monitoring
        meta.helm.sh/release-namespace: monitoring
    name: archive-node
    namespace: monitoring
    labels:
        app: archive-node
        app.kubernetes.io/instance: monitoring
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 21.0.4
        chart: kube-prometheus-stack-21.0.4
        heritage: Helm
        release: monitoring
spec:
    clusterIP: None
    ports:
    - name: archive-node
      targetPort: archive-node
      port: 9615
