---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: monitoring

helmCharts:
  # black-box helm chart
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 7.0.0
    releaseName: black-box
    namespace: monitoring
    valuesFile: values.yaml
generatorOptions:
  disableNameSuffixHash: true

components:
  - "../../components/prom-stack"
  - "../../components/grafana-dashboards"
  - "../../components/production-service-monitors"
