---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 17.3.11
    releaseName: redis
    valuesFile: values.yaml
    namespace: default
