---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-secret
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgBhdhb7LgbdJI4TlgLgUlJZJGta5MIXzdvBjHkaBMY/1jgBuLo6luFoA5t0InHvtv3bm/vCG8zz50VtkFXUCl0AZpiKEClRNLyi3ENaSS5dWDdUDvy7EvjsAEhb35pDDLfmk/dd9NLElPI6Ow3GIa5dk5g391UgbyALDPRmAhUufAjx1u+5RFLnKTlsjd1h4NO4Z4YgdbgbCS7/Y7yMG/9EX9i8km8RixWIvM36RdI2i6vi7Pgb2X8SQDbRw4Fj7FhVw77Hunc/72yY2e1jQB9Wxzc/l/fdaR9NDfxWQPZQif7kzkscALlrioV4OA1R4EFtC7rDAkm5aDEgypU78lTHWq5yXszsU0WrlMMni0hkpkgf8SVWCj6hdvYT2nive4ExbVCQMPNu9AgBgozM0GCJBDrlLSQIjqt2kgX64ZZDX3xcbIt9i7Qm2dCFLPVmiHZ+75OSebn3MIEGgdYZ1CH+NYehoBDvNRrzw75t2iCDWBg22YB4LgfmRGrgA7OrPmQI4tBVcJ0dQ3Oq4EekZ5zEYAnLigRDAK+tdkWS1mEINxRwmPmpYDOXl930SEyzC4aBymBV2mX2We3Zxlx+2NJnKagKqj9T9l9bj8Q6HUmr0B51KHaUZz+L7wAqySi7Exh6xi+HAE7aAOH0kT+NeMPLZZTOVA+I9DXRiECbZ9Q4KfB2NzX35rskQXeT6Og3vd/D6L28TEiu36Ot23RKr5mz8WwZIEr+So4KDLs/D2gmBAZqwmVemhqysl6yIXp6yiLv4Bq6I3dR1VX8zY3wth02YtzSGCOmJlU+NeLLm99alzNNTWjdT/HHnscyvszhd4mcbWkdrJxUfJecG4DZJt7P+xM5NBIRiOg=
  template:
    metadata:
      creationTimestamp: null
      name: discord-secret
      namespace: monitoring
