---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-creds
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCxTs9eyCkAQvk072C/Dst8WNg/61qcqrbkAZo3gLH6IOFVNdd11vSuoMGdU9UrwdDG867IzgzOyqoMDEySidVQZJapUibjVh4NRlfAyv9Njoj+opR/rDm/qi+y+dDq8sxq3enjrvs8kiCJA5sd7rPC9bcFS4setimEvh3k8lB/gTu7NBBr4Pgqz4cKF7i8u9KsJ3VtSfD6xfydGiS41O8zvb7nLGSVm5HexH07RbY0K1z3inMPzqvbS8F1rG+2nL0KLpHHJ9rgdlOKK3EMaXFHRrGgdg04t/yUiYL0C0MxghK9w8jhYPDhBhI53kgSY51ty/TwjWbJogXLILscADi6e2r0Sg9OHYPkKrpb1ToGoe6gSEWmhfAbP4OT9K32GWKp2qFhiZVMlxeJQbYMYeENXvLNxJx6/Oct+pYdHzQgb+ueIAz3SrbJLMSjnGdpi1sr58BsLY256WdegokOHXgj51897Oek9KzU38kdXPeVqEQ0k4u0osh3jrnlYDtyj+t+2amHR7cxkRoATNcZbQ3XU6hpsOkK2wcvHHzV7Zr85Kiy/K6R7X/WJcwMNV1/V0jwzuC8ZiqWsJKrmm2AFaS14BCVC7fLrQt0IJwK+DC2XOcCtiqdfn+TNhtb7Kf3baB0VoBRNeIi/JoVtKXOo+/PKuYBh/0f16Ms4QtWMZwGMUi4bwo9YdReYZ+qTSHiivNVvNoyCx2eXeGIk/iFl0Uz5g==
    admin-user: AgBxjUwXlQm4v8ITsOEffuDfKUm9SgA2lK9jZvWyLXn0DF4eJ5FKgtDEqfSK3JRbF51XLbPzYULL4KJwdnrmcwvSsJw8Vv/Nwv74EF9tjkJZzuPCWg9W3OgLtF9FaJZK7dx2nCjKuEbY0RYNYOxm13i/SqBIGOUIhtupp/0wFYSFQ/G4+IM/V+LxBrOOnqxqGuFYq85/Q5RYOnWgmcJ0hbrTSvIdqhc/CwPod6Ff/X/ltj73eF+EDSpXOCY1vixShusRXktOX8QMi5lR4DwW8FfMXRitvQc0UpLcSZ6wQAzx+0RNelstjwV/5KiaWwmXK2HMHeLpFvwwc2r7nN6Rk8+RXcdynrWBT38NPLnPiM5LIPb1fEfDzVgRpXnaoIwWHMeM9yaZ4DPaJMfSVz9bGAhj/nwxjc40fa2eVLO2z1gndQY1BfDsnXJzj2GusYSOzK/++xUKRl+eLPNt2KmKljpTV1Y7Fy9uXgDTToe4cuBtnjp7rsr0+yyBPvCB6RAP8On1TLwg8aczEiY3ZkjQmoWGcBI86kgvp59HN9+S1MADDRg/55coxynixzYP9eNrhkVNnfa8YPy7E/DoHRRnI+FW7CZiT1E+HuRr8n2il8BFvVdFRsbwDJHpFiQnKOfUFnqNy+e231I+7LptrTc1eReqnjKgbSbitxo3ITWnmKFnf2/bbw634TARyey5+cAfsvwf+9vG7Q==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-creds
      namespace: monitoring
