---
githubConfigUrl: "https://github.com/dappforce"

githubConfigSecret: gh-pat-secret

maxRunners: 12

minRunners: 1

runnerGroup: "Private Repos Runner"

containerMode:
  type: "dind"

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
