---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-loki
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
      name: fluent-bit-loki
    spec:
      containers:
        - image: fluent-bit-loki
          imagePullPolicy: IfNotPresent
          name: fluent-bit-loki
          ports:
            - containerPort: 2020
              name: http-metrics
              protocol: TCP
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: config
            - mountPath: /run/fluent-bit
              name: run
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
      restartPolicy: Always
      serviceAccount: fluent-bit-loki
      serviceAccountName: fluent-bit-loki
      terminationGracePeriodSeconds: 10
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - configMap:
            defaultMode: 420
            name: fluent-bit-loki
          name: config
        - hostPath:
            path: /run/fluent-bit
            type: ""
          name: run
        - hostPath:
            path: /var/log
            type: ""
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
