---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: default
spec:
  encryptedData:
    redis-password: AgCuE+O1bOjY5hlFacc3/e4Korw6qP8NbRcchOD6nqbvH7AWZiFQmCrcXXZUTmHdoZdoyni1F39cdbMftSRG9cN8e/PnS5grtVk13SZhUjfcqhWWKEcAEl1ODy+83LtJjq7VE46l2hu+gth3NXhm0H28YM4oiIdrZucCBixXQYBZdEs0vCTEu+U/kKbqYDwWZ4g494NDkQklNPrk99ZtQtnShqpi37vjrI5qgYk3x8FC60WZ6e4zrWka6YvnWiY339cqm53olxUsmRaZATtFQC+nWzAUU+l2xtyarhT5n3c3rI3tHol0ftvweXu21Y873dvwzPHWm/Y6XgK15zFl+PhaUqvbEkmsP4/dP07wJKnq4984APIPR3zS1ZeSqygwZhStvJ180XHSJ4RITbojFGrMahRr/5p1nstR/0ms02uDXDfKR6iWR0JLcNSDg276YBNxZbxGzRbzV2FWrbv/Yq31O22CXE+09a7nKsXaLdxP02Z+TsGMAIIYo2FZJH2JUtdFEKmy2Ge+mGBiHUpT3PA3yn5U6SvpO2gwriNYmWztEtTAjuTxkZWV/LrP2cJwRBgWOkCX4nCQ1LvntbjlweTeOpP8p/JgWPJWM6PKLQwQ+4dXUqCKRaY5cMc2lp8wFOmW576n97IEzFSlA6j5d+05onIIFwQlj5uZcuF3gDvpPZb/sHljf8GHvucI2chXJVXP22o43o6RvUewsiFCeHaP
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: default
