---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring

  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 37.2.0
    chart: kube-prometheus-stack-37.2.0
    heritage: Helm
    release: monitoring

  name: argocd-metrics
  namespace: argocd
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring

  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 37.2.0
    chart: kube-prometheus-stack-37.2.0
    heritage: Helm
    release: monitoring

  name: argocd-server-metrics
  namespace: argocd
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring

  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 37.2.0
    chart: kube-prometheus-stack-37.2.0
    heritage: Helm
    release: monitoring

  name: argocd-repo-server-metrics
  namespace: argocd
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring

  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 37.2.0
    chart: kube-prometheus-stack-37.2.0
    heritage: Helm
    release: monitoring

  name: argocd-applicationset-controller-metrics
  namespace: argocd
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
