---
name: GH Runner Packer

on:
  workflow_dispatch:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          working_directory: packer/DO/gh-runner
          command: fix
          target: template.json
        env:
          PACKER_LOG: 1
          DO_TOKEN: ${{ secrets.DO_TOKEN }}

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          working_directory: packer/DO/gh-runner
          arguments: -var-file=variables.json
          target: template.json
        env:
          PACKER_LOG: 1
          DO_TOKEN: ${{ secrets.DO_TOKEN }}

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var-file=variables.json"
          target: template.json
          working_directory: packer/DO/gh-runner
        env:
          PACKER_LOG: 1
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
